#!/usr/bin/env bash
# :D
awk '
{
    key = $1 " " $9;

    # Increment the counter for this unique key.
    counts[key]++;
}

END {
    for (key in counts) {
        # The required output format is: OCCURRENCE_NUMBER IP HTTP_CODE
        # We print the count (counts[key]) followed by the key (IP HTTP_CODE).
        print counts[key], key
    }
}' apache-access.log | sort -nr
