#!/usr/bin/env bash
# Group by IP and HTTP status, sorted by occurrences

awk '{count[$1, $9]++} END {for (key in count) {
    split(key, arr, SUBSEP)
    print count[key], arr[1], arr[2]
}}' apache-access.log | sort -rn
