#!/usr/bin/env bash
# :D
hour=0
while [ $hour -le 12 ]; do
    minute=1
    while [ $minute -le 59 ]; do
        printf "%d\n" $minute
        ((minute++))
    done
    ((hour++))
    printf "Hour: %d\n" $hour
done
