#!/usr/bin/env bash
# Check if the file exists
if [ -e "$FILE" ]; then
    echo "school file exists"

    # Check if the file is empty
    if [ ! -s "$FILE" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    # Check if it is a regular file
    if [ -f "$FILE" ]; then
        echo "school is a regular file"
    fi

else
    echo "school file does not exist"
fi
