#!/usr/bin/env bash
# :D
PIDFILE="/var/run/myscript.pid"

# Create PID file
echo $BASHPID > "$PIDFILE"

# --- Signal Handlers ---
sigterm_handler() {
    echo "I hate the kill command"
    rm -f "$PIDFILE"
    exit 0
}

sigint_handler() {
    echo "Y U no love me?!"
}

sigquit_handler() {
    rm "$PIDFILE"
    exit 0
}

# Trap signals
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

# --- Main Loop ---
while true; do
    echo "To infinity and beyond"
    sleep 1
done
